name: caaso_app
description: "Flutter App for Sócio Caaso"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+8
environment:
  sdk: ^3.6.1
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  qr_flutter: ^4.1.0
  google_fonts: ^6.2.1
  provider: ^6.1.2
  firebase_core: ^3.10.1
  firebase_analytics: ^11.4.1
  firebase_auth: ^5.4.1
  cloud_firestore: ^5.6.2
  google_sign_in: ^6.2.2
  http: ^1.3.0
  flutter_secure_storage: ^9.2.4
  intl: ^0.20.2
  confetti: ^0.8.0
  simple_icons: ^10.1.3
  url_launcher: ^6.3.1
  flutter_launcher_icons: ^0.14.3
  mobile_scanner: ^6.0.6
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/codelab.png
    - assets/google.png