// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt3n03EyhXkNdYTKM_jws5w11iBESNr8U',
    appId: '1:425041072425:web:80bb7e910a55a8f9f6e738',
    messagingSenderId: '425041072425',
    projectId: 'caaso-app',
    authDomain: 'caaso-app.firebaseapp.com',
    storageBucket: 'caaso-app.firebasestorage.app',
    measurementId: 'G-89F460SNWR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoab1820rbUMdr66lRh9UFh9a65fn661w',
    appId: '1:425041072425:android:8267ec4abceb9823f6e738',
    messagingSenderId: '425041072425',
    projectId: 'caaso-app',
    storageBucket: 'caaso-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDarBrQmek-ms859ah9d4yH7KscxaQoq6o',
    appId: '1:425041072425:ios:dfdfb64ce96a1fa3f6e738',
    messagingSenderId: '425041072425',
    projectId: 'caaso-app',
    storageBucket: 'caaso-app.firebasestorage.app',
    iosBundleId: 'com.example.caasoApp',
  );

}